### ISSUE TITLE
win7系统上路径解析出错

### ISSUE THREAD

**Issue by Claiyre** [picidaejs/picidaejs#7]
**Choose one:** is this a 🐛 bug report or 🙋 feature request?
 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

```javascript
{
  'your': { 'config': 'here' }
}
```

### 😯 Current Behavior

run `picidae start`
### 🔦 Context

a lot of warnings, and the pages can't be rendered properly！ 
![194d43fd44fd454e8ee217718c40e1f8](https://user-images.githubusercontent.com/18069718/35130281-0d643004-fcfb-11e7-8c5d-590a6ab72570.png)

### 🌍 Your Environment

| Software         | Version(s)
| ---------------- | ----------
| Picidae          |  2.1.6
| Node             | 8.9.0
| npm/Yarn         | 5.5.1
| Operating System | win7

**Comment by imcuttle** [comment]
请使用 `npm i picidae --save` 在本地安装 picidae 使用
